page-redirect.php

You can see this working on atwood, just make a page and add the link you want to redirect to. 
https://caa.atwood.mlacommons.org/wp-admin/post.php?post=427&action=edit
To test:
https://caa.atwood.mlacommons.org/faq

Adding a reusable page template for redirects

---

js/boss-child.js

Changing the wording of the privacy options and submission success text. 
See:
https://trello.com/c/y5sLJlx6/367-fix-site-privacy-options-in-create-a-site-process

Create a site privacy option

---

js/boss-child.js

Adding AreYouSure, also making site message more specific to the create a site page. 
http://trello.com/c/WS4uiekZ/351-update-group-email-settings

Update blog settings page js

---

js/boss-child.js

Fixing the jquery so that it finds the correct folder id to sort.

Fixing sorting within folders

---

docs/docs-folder-loop.php
js/boss-child.js

See https://trello.com/c/S0F9S1Yw/437-improve-docs

Fixing drop down issue with select and sorting of folders

---

js/boss-child.js

Adding a fix for drop down hidden values

Adding a small fix for Doc dropdowns

---

buddypress/assets/emails/single-bp-email.php

See https://trello.com/c/u0qMiSzI/453-improve-hc-emails

Removing header and personalization

---

buddypress/assets/emails/single-bp-email.php

Making sure these changes only affect Humanities Commons

Restricting header and personalization changes 

---

buddypress/assets/emails/single-bp-email.php

Adding a smaller header to HC emails.

Adding small header to hc email

---

buddypress/assets/emails/single-bp-email.php

Adding logo and allowing the ability to set some aspects of the header via the "Customize" option in the dashboard.

HC email header

---

js/boss-child.js

See https://trello.com/c/lQuEUaQj/508-carol-wants-to-delete-files-from-election-committee-group-without-generating-notifications-for-each

Adding detection of checkbox for silent notification

---

js/boss-child.js

Fixing jquery code to remove the no notifications check if the checkbox is unchecked and changing id to class.

Fixing jquery

---

js/boss-child.js

See 
https://trello.com/c/CtROeNjo/465-clarify-visibility-descriptions-for-sites

Unifying verbage for site clarification

---

js/boss-child.js

I introduced a javascript error with my last pull request. (clarify visibility descriptions for sites)

Fixing wrong right parenthesis on second clause

---

js/boss-child.js

Adding public options to group blog creation.

Add public options to group blog and fix visibility wording

---

js/boss-child.js

This is connected to this pull request:
https://github.com/mlaa/hc-custom/pull/107

Adding delete button via jquery

---

js/boss-child.js

Adding nonce associated with the js file for security

Adding nonce to AJAX request

---

buddypress/groups/single/admin.php
docs/single/edit-inner.php

Implements new functions in hc-custom to give the user the ability to set default toggles in Docs. 
https://trello.com/c/Rr7JRbIJ/612-on-create-new-doc-screen-collapse-by-default-associated-group-group-folders-tags-and-parent-leave-access-expanded

Crete doc toggles

---

buddypress/blogs/create.php

Overriding the create a site template to change the text and other elements of the page.

Override create site template

---

js/boss-child.js

Only changing the body class if it is set in group pages

Fixing general activity page
